Ws Cube : Channel:

Text Pre-processing:

1.Text Cleaning: In-text cleaning we do HTML tag removing , emoji handling , spelling checker , etc 
Basic Preprocessing : in basic preprocessing we do tokenization (word or sent tokenization , stop word removal 
,digit reomval , lower casing.
2. Advance Preprocessing : in this step we do POS tagging , parsing and Coreference resolution>

Understanding Textual Data:

                            Textual Data 
Elements of Text :
. Hierarchy of Text
. Tokens
. Vocabulary
. Punctuation
. Part of speech
. Root of a word
. Base of a word
. stop words.

In [11]:
x = " Natural language processing has its roots in the 1950s.[2] Already in 1950, Alan Turing publishedan article titled Computing Machinery and Intelligence which proposed what is now called the Turing teas a criterion of intelligence, though at the time that was not articulated as a problem separate fromartificial intelligence. Natural language processing has its roots in the 1950s.[2] Already in 1950, Alan Turing published an article titled Computing Machinery and Intelligence which proposed what is now called the Turing test as a criterion of intelligence, though at the time that was not articulated as a problem separate from artificial intelligence. "

Text Pre-processing Techniques:

. Lower casing               . Tokenization
. Remove HTML Tags           .Stop words Removal
. Removing URLs              . N-Grams
. Removing Punctuation       . Stemming\Lemmatization
. Chat word Treatment
. Spelling Correction

Tokenization:

In [9]:
var = " Natural language processing has its roots in the 1950s.[2] Already in 1950, Alan Turing publishedan .article titled Computing Machinery and Intelligence which proposed what is .now called the Turing teas a criterion of intelligence, though at the time .that was not articulated as a problem separate fromartificial intelligence. Natural language processing has its roots in the 1950s.[2] Already in 1950. Alan Turing published an article titled Computing Machinery and Intelligence which proposed what. is now called the Turing test as a criterion of intelligence, though at the time that was not articulated as a problem separate from artificial intelligence. "

In [10]:
var

' Natural language processing has its roots in the 1950s.[2] Already in 1950, Alan Turing publishedan .article titled Computing Machinery and Intelligence which proposed what is .now called the Turing teas a criterion of intelligence, though at the time .that was not articulated as a problem separate fromartificial intelligence. Natural language processing has its roots in the 1950s.[2] Already in 1950. Alan Turing published an article titled Computing Machinery and Intelligence which proposed what. is now called the Turing test as a criterion of intelligence, though at the time that was not articulated as a problem separate from artificial intelligence. '

In [4]:
from nltk.tokenize import word_tokenize,sent_tokenize

In [5]:
sent = sent_tokenize(var)

In [6]:
sent

[' Natural language processing has its roots in the 1950s.',
 '[2] Already in 1950, Alan Turing publishedan .article titled Computing Machinery and Intelligence which proposed what is .now called the Turing teas a criterion of intelligence, though at the time .that was not articulated as a problem separate fromartificial intelligence.',
 'Natural language processing has its roots in the 1950s.',
 '[2] Already in 1950.',
 'Alan Turing published an article titled Computing Machinery and Intelligence which proposed what.',
 'is now called the Turing test as a criterion of intelligence, though at the time that was not articulated as a problem separate from artificial intelligence.']

In [12]:
for i in sent:
    print(i)
    print()

 Natural language processing has its roots in the 1950s.

[2] Already in 1950, Alan Turing publishedan .article titled Computing Machinery and Intelligence which proposed what is .now called the Turing teas a criterion of intelligence, though at the time .that was not articulated as a problem separate fromartificial intelligence.

Natural language processing has its roots in the 1950s.

[2] Already in 1950.

Alan Turing published an article titled Computing Machinery and Intelligence which proposed what.

is now called the Turing test as a criterion of intelligence, though at the time that was not articulated as a problem separate from artificial intelligence.

In [7]:
word = word_tokenize(var)

In [8]:
word

['Natural',
 'language',
 'processing',
 'has',
 'its',
 'roots',
 'in',
 'the',
 '1950s',
 '.',
 '[',
 '2',
 ']',
 'Already',
 'in',
 '1950',
 ',',
 'Alan',
 'Turing',
 'publishedan',
 '.article',
 'titled',
 'Computing',
 'Machinery',
 'and',
 'Intelligence',
 'which',
 'proposed',
 'what',
 'is',
 '.now',
 'called',
 'the',
 'Turing',
 'teas',
 'a',
 'criterion',
 'of',
 'intelligence',
 ',',
 'though',
 'at',
 'the',
 'time',
 '.that',
 'was',
 'not',
 'articulated',
 'as',
 'a',
 'problem',
 'separate',
 'fromartificial',
 'intelligence',
 '.',
 'Natural',
 'language',
 'processing',
 'has',
 'its',
 'roots',
 'in',
 'the',
 '1950s',
 '.',
 '[',
 '2',
 ']',
 'Already',
 'in',
 '1950',
 '.',
 'Alan',
 'Turing',
 'published',
 'an',
 'article',
 'titled',
 'Computing',
 'Machinery',
 'and',
 'Intelligence',
 'which',
 'proposed',
 'what',
 '.',
 'is',
 'now',
 'called',
 'the',
 'Turing',
 'test',
 'as',
 'a',
 'criterion',
 'of',
 'intelligence',
 ',',
 'though',
 'at',
 'the',
 'time',
 'that',
 'was',
 'not',
 'articulated',
 'as',
 'a',
 'problem',
 'separate',
 'from',
 'artificial',
 'intelligence',
 '.']

In [16]:
for i in word:
    print(i)

Natural
language
processing
has
its
roots
in
the
1950s
.
[
2
]
Already
in
1950
,
Alan
Turing
publishedan
.article
titled
Computing
Machinery
and
Intelligence
which
proposed
what
is
.now
called
the
Turing
teas
a
criterion
of
intelligence
,
though
at
the
time
.that
was
not
articulated
as
a
problem
separate
fromartificial
intelligence
.
Natural
language
processing
has
its
roots
in
the
1950s
.
[
2
]
Already
in
1950
.
Alan
Turing
published
an
article
titled
Computing
Machinery
and
Intelligence
which
proposed
what
.
is
now
called
the
Turing
test
as
a
criterion
of
intelligence
,
though
at
the
time
that
was
not
articulated
as
a
problem
separate
from
artificial
intelligence
.

Stop Words Removal:

In [40]:
var

' Natural language processing has its roots in the 1950s.[2] Already in 1950, Alan Turing publishedan .article titled Computing Machinery and Intelligence which proposed what is .now called the Turing teas a criterion of intelligence, though at the time .that was not articulated as a problem separate fromartificial intelligence. Natural language processing has its roots in the 1950s.[2] Already in 1950. Alan Turing published an article titled Computing Machinery and Intelligence which proposed what. is now called the Turing test as a criterion of intelligence, though at the time that was not articulated as a problem separate from artificial intelligence. '

In [43]:
from nltk.tokenize import word_tokenize,sent_tokenize

In [44]:
var_new = word_tokenize(var)

In [23]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\123/nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [45]:
from nltk.corpus import stopwords
from string import punctuation

In [29]:
stop = stopwords.words('english')

In [37]:
stop_word_list = list(punctuation)+stop

In [46]:
for i in var_new:
    if i not in stop_word_list:
        print(i)

Natural
language
processing
roots
1950s
2
Already
1950
Alan
Turing
publishedan
.article
titled
Computing
Machinery
Intelligence
proposed
.now
called
Turing
teas
criterion
intelligence
though
time
.that
articulated
problem
separate
fromartificial
intelligence
Natural
language
processing
roots
1950s
2
Already
1950
Alan
Turing
published
article
titled
Computing
Machinery
Intelligence
proposed
called
Turing
test
criterion
intelligence
though
time
articulated
problem
separate
artificial
intelligence

Stemming and Lemmatization:

In [68]:
from nltk.stem import PorterStemmer

In [69]:
p = PorterStemmer()

In [123]:
p.stem('change')

'chang'

Lemmatization:

In [102]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to C:\Users\123/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [106]:
from nltk.stem import WordNetLemmatizer

In [107]:
wl = WordNetLemmatizer()

In [124]:
wl.lemmatize("mice")

'mouse'

Sheriyans AI School: Channel

In [81]:
import numpy as np
import pandas as pd

In [82]:
df = pd.read_csv(r'C:\Users\123\Desktop\train.txt',sep = ';',header=None,names=['text','emotion'])

In [83]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [84]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [85]:
unique_emotions=df['emotion'].unique()
emotion_numbers= {}
i = 0
for emo in unique_emotions:
    emotion_numbers[emo] = i
    i +=1
df['emotion'] = df['emotion'].map(emotion_numbers)

In [86]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

Text Cleaning:

1.Lowercasing:

In [87]:
df['text']=df['text'].apply(lambda x: x.lower())

In [88]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

2.Remove Punctuation:

In [89]:
import string
from string import punctuation

In [90]:
def remove_punc(txt):
    return txt.translate(str.maketrans('','',string.punctuation))

In [91]:
df['text']=df['text'].apply(remove_punc)

In [92]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

3.Remove Numbers:

In [93]:
def remove_numbers(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new

df['text'] = df['text'].apply(remove_numbers)

In [94]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

4.Remove URLs/Links:

5.Remove HTML Tags:

6.Remove Emojis & Special characters:

In [39]:
# def remove_numbers(txt):
#     new = ""
#     for i in txt:
#         if not i.isascii():
#             new = new + i
#     return new

# df['text'].apply(remove_numbers)

0
1
2
3
4
        ..
15995
15996
15997
15998
15999
Name: text, Length: 16000, dtype: object

In [95]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

7.Remove Stopwords:

In [96]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize,sent_tokenize

In [60]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to C:\Users\123/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to C:\Users\123/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [97]:
stop_words = set(stopwords.words('english'))

In [98]:
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [99]:
df.loc[1,'text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [109]:
def remove_stopwords(txt):
    words = txt.split()
    cleaned = []
    for i in words:
        if not i in stop_words:
            cleaned.append(i)

    return ' '.join(cleaned)

In [111]:
txt = 'This is Sami my name are sami is  and'
remove_stopwords(txt)

'This Sami name sami'

In [112]:
df['text']=df['text'].apply(remove_stopwords)

In [113]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

CampusX: Channel

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv(r'C:\Users\123\Desktop\IMDB Dataset.csv')

In [4]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

In [13]:
df.describe()

                                                   review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

In [14]:
df.duplicated().value_counts()

False    49582
True       418
Name: count, dtype: int64

In [17]:
df.drop_duplicates(inplace=True)

In [18]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[49582 rows x 2 columns]

Preprocessing:

1.Lowercasing:

In [19]:
df['review']=df['review'].str.lower()

In [20]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. <br /><br />the...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[49582 rows x 2 columns]

2.Remove HTML tags:

In [21]:
import re

In [22]:
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'',text)

In [23]:
#test on example:
text = "<html><body><p> Movie 1</p><p> Actor - Aamir Khan </p></p> Click here to <a href-'http://google.com'> download"
remove_html_tags(text)

' Movie 1 Actor - Aamir Khan  Click here to  download'

In [24]:
# apply on data set
df['review']=df['review'].apply(remove_html_tags)

In [25]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. the filming tec...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[49582 rows x 2 columns]

3.Remove URLs Tags:

In [26]:
def remove_url_tags(text):
    url = re.compile(r'https?://\S+|www\.\S+')
    return url.sub(r'',text)

In [27]:
#example
text = 'check out my notebook https://www.kaggle.com/campusx/notebook8223fc1abb'
remove_url_tags(text)

'check out my notebook '

In [28]:
df['review']=df['review'].apply(remove_url_tags)

In [29]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

4.Remove Punctuations:

In [30]:
import nltk
import string
from string import punctuation

In [31]:
exclude = string.punctuation
print(exclude)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

In [32]:
def remove_punc(text):
    return text.translate(str.maketrans('','',exclude))

In [33]:
#exanple
text='s.a,m/,?i'
remove_punc(text)

'sami'

In [34]:
df['review']=df['review'].apply(remove_punc)

In [35]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production the filming tech...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

5.Chat word treatment:

In [36]:
chatwords = {
    "AFAIK": "As Far As I Know",
    "AFK": "Away From Keyboard",
    "ASAP": "As Soon As Possible",
    "ATK": "At The Keyboard",
    "ATM": "At The Moment",
    "A3": "Anytime, Anywhere, Anyplace",
    "BAK": "Back At Keyboard",
    "BBL": "Be Back Later",
    "BBS": "Be Back Soon",
    "BFN": "Bye For Now",
    "B4N": "Bye For Now",
    "BRB": "Be Right Back",
    "BRT": "Be Right There",
    "BTW": "By The Way",
    "B4": "Before",
    "B4N": "Bye For Now",
    "CU": "See You",
    "CUL8R": "See You Later",
    "CYA": "See You",
    "FAQ": "Frequently Asked Questions",
    "FC": "Fingers Crossed",
    "FWIW": "For What It's Worth",
    "FYI": "For Your Information",
    "GAL": "Get A Life",
    "GG": "Good Game",
    "GN": "Good Night",
    "GMTA": "Great Minds Think Alike",
    "GR8": "Great!",
    "G9": "Genius",
    "IC": "I See",
    "ICQ": "I Seek you (also a chat program)",
    "ILU": "ILU: I Love You",
    "IMHO": "In My Honest/Humble Opinion",
    "IMO": "In My Opinion",
    "IOW": "In Other Words",
    "IRL": "In Real Life",
    "KISS": "Keep It Simple, Stupid",
    "LDR": "Long Distance Relationship",
    "LMAO": "Laugh My A.. Off",
    "LOL": "Laughing Out Loud",
    "LTNS": "Long Time No See",
    "L8R": "Later",
    "MTE": "My Thoughts Exactly",
    "M8": "Mate",
    "NRN": "No Reply Necessary",
    "OIC": "Oh I See",
    "PITA": "Pain In The A..",
    "PRT": "Party",
    "PRW": "Parents Are Watching",
    "QPSA": "Que Pasa?",
    "ROFL": "Rolling On The Floor Laughing",
    "ROFLOL": "Rolling On The Floor Laughing Out Loud",
    "ROTFLMAO": "Rolling On The Floor Laughing My A.. Off",
    "SK8": "Skate",
    "STATS": "Your sex and age",
    "ASL": "Age, Sex, Location",
    "THX": "Thank You",
    "TTFN": "Ta-Ta For Now!",
    "TTYL": "Talk To You Later",
    "U": "You",
    "U2": "You Too",
    "U4E": "Yours For Ever",
    "WB": "Welcome Back",
    "WTF": "What The F...",
    "WTG": "Way To Go!",
    "WUF": "Where Are You From?",
    "W8": "Wait...",
    "7K": "Sick:-D Laugher",
    "TFW": "That feeling when",
    "MFW": "My face when",
    "MRW": "My reaction when",
    "IFYP": "I feel your pain",
    "LOL": "Laughing out loud",
    "TNTL": "Trying not to laugh",
    "JK": "Just kidding",
    "IDC": "I don’t care",
    "ILY": "I love you",
    "IMU": "I miss you",
    "ADIH": "Another day in hell",
    "IDC": "I don’t care",
    "ZZZ": "Sleeping, bored, tired",
    "WYWH": "Wish you were here",
    "TIME": "Tears in my eyes",
    "BAE": "Before anyone else",
    "FIMH": "Forever in my heart",
    "BSAAW": "Big smile and a wink",
    "BWL": "Bursting with laughter",
    "LMAO": "Laughing my a** off",
    "BFF": "Best friends forever",
    "CSL": "Can’t stop laughing"
}

In [37]:
def chat_conversation(text):
    new_text=[]
    for word in text.split():
        if word.upper() in chatwords:
            new_text.append(chatwords[word.upper()])
        else:
            new_text.append(word)
    return ' '.join(new_text)

In [40]:
#Example test
text = 'IMHO he is the best'
chat_conversation(text)

'In My Honest/Humble Opinion he is the best'

In [39]:
df['review']=df['review'].apply(chat_conversation)

In [41]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production the filming tech...  positive
2      i thought this was a wonderful way to spend Te...  positive
3      basically theres a family where a little boy j...  negative
4      petter matteis love in the Tears in my eyes of...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  im going to have to disagree with the previous...  negative
49999  no one expects the star trek movies to be high...  negative

[49582 rows x 2 columns]

6.spelling Correction:

In [55]:
!pip install textblob

Collecting textblob
  Downloading textblob-0.19.0-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: nltk>=3.9 in c:\users\123\anaconda3_new9\lib\site-packages (from textblob) (3.9.1)
Requirement already satisfied: click in c:\users\123\anaconda3_new9\lib\site-packages (from nltk>=3.9->textblob) (8.1.8)
Requirement already satisfied: joblib in c:\users\123\anaconda3_new9\lib\site-packages (from nltk>=3.9->textblob) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\123\anaconda3_new9\lib\site-packages (from nltk>=3.9->textblob) (2024.11.6)
Requirement already satisfied: tqdm in c:\users\123\anaconda3_new9\lib\site-packages (from nltk>=3.9->textblob) (4.67.1)
Requirement already satisfied: colorama in c:\users\123\anaconda3_new9\lib\site-packages (from click->nltk>=3.9->textblob) (0.4.6)
Downloading textblob-0.19.0-py3-none-any.whl (624 kB)
   ---------------------------------------- 0.0/624.3 kB ? eta -:--:--
   --------------------------------- ------ 524.3/624.3 kB 4.7 MB/s eta 0:00:01
   ---------------------------------------- 624.3/624.3 kB 2.1 MB/s eta 0:00:00
Installing collected packages: textblob
Successfully installed textblob-0.19.0

In [6]:
from textblob import TextBlob

In [7]:
def spell_correction(text):
    text_correct=TextBlob(text)
    return text_correct.correct().string

In [8]:
text = 'crtein condtions durringg severl generationnns aree modifid in the same mannir'
spell_correction(text)

'certain conditions during several generations are modified in the same manner'

In [ ]:
df['review']=df['review'].apply(spell_correction)

In [5]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

7.Stopwords:

In [6]:
import nltk

In [7]:
from nltk.corpus import stopwords

In [8]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [15]:
def remove_stopwords(text):
    new_text = []
    for word in text.split():
        if word.lower() in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)
    return ' '.join(new_text)

In [16]:
#example
text = 'probably my all-time favourite movie, a story of selflessness ,this sami are'
remove_stopwords(text)

'probably  all-time favourite movie,  story  selflessness ,this sami '

In [ ]:
df['review']=df['review'].apply(remove_stopwords)

In [ ]:
df.head()

8.Handling Emojis:

In [3]:
import emoji

ModuleNotFoundError: No module named 'emoji'

In [4]:
pip install emoji

Note: you may need to restart the kernel to use updated packages.

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001F58E1738C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/emoji/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001F58E27C410>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/emoji/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001F58E27C690>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/emoji/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001F58E27C910>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/emoji/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001F58E27CB90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/emoji/
ERROR: Could not find a version that satisfies the requirement emoji (from versions: none)
ERROR: No matching distribution found for emoji

In [ ]:
def replace_emojis(text):
    return emoji.demojize(text)

In [2]:
replace_emojis('Pyhton is 😎')

NameError: name 'replace_emojis' is not defined

In [1]:
print('fnh')

fnh

In [2]:
import sys
print(sys.executable)

C:\Users\123\anaconda3_new9\python.exe